### PR TITLE
Fixed support for repos using 'file' protocol

### PR DESCRIPTION
**Pull request by gregoryo2014**
This change enables using the file protocol for a local repository created with pkg repo.

### CODE REVIEW

**Comment by xaque208** [comment]
Apologies for the delay.  I don't believe that to be the correct change for the stated result.  In any case, this probably needs a test, and I'm finding that line hard to read.  In my opinion this logic should be moved into puppet so that only a single variable is used in the url's string.

**Comment by gregoryo2014** [comment]
No dramas. It works for me, but working is obviously a different issue to the most desirable way to have it written. I'll leave it with you to decide how you want to handle it.

**Comment by xaque208** [comment]
A test or an update to the readme or something would help in my opinion.

**Comment by gregoryo2014** [comment]
This is no longer required, since the module works with protocol => 'file', packagehost => ''. It could be that this always worked, but I've not tried it before.

**Comment by xaque208** [comment]
Thanks for coming back to it.

**Pull request closed without merging**
